#!/usr/bin/env python

import os
import sys

settings_file = "_discharge.py"

dct = {'__file__': os.path.realpath('_discharge.py')}

execfile(settings_file, dct)

site = dct['site']

if len(sys.argv) == 2 and sys.argv[1] == 'build':
    site.build()
else:
    raise ValueError("incorrect usage")
